version: '3.3'
services:

  database:
    image: postgres
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-service
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"

  search-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: search-service
    volumes:
      - /var/db/data/elasticsearch:/Users/docker_volumes/elasticsearch_bkp
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  config-server:
    container_name: config-server
    build: ./config-server
    volumes:
      - ./config-data:/var/config-data
    ports:
      - "8888:8888"
    links:
      - eureka-server
    depends_on:
      - eureka-server

  store-service:
    container_name: store-service
    build: ./store-service
    ports:
      - "8090:8090"
    links:
      - eureka-server
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server

  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8081:8081"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    links:
      - eureka-server
      - redis
    restart: on-failure
    depends_on:
      - database
      - search-service
      - eureka-server
      - config-server

  gateway-server:
    container_name: gateway-server
    build: ./gateway-server
    ports:
      - "8765:8765"
    links:
      - eureka-server
    restart: on-failure
    depends_on:
      - eureka-server
      - product-service

volumes:
  postgres_data:
    driver: local
  esdata1:
    driver: local