server:
  port: 8077
spring:  jpa:    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:      ddl-auto: update
  datasource:
    platform: postgres    url: jdbc:postgresql://localhost:5432/address    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver  cloud:    config:      uri: http://localhost:8888  application:    name: address-service